import { Failure } from '@/types';

export const INITIAL_SEED_FAILURES: Omit<Failure, 'embedding'>[] = [
  // 업무/취업
  {
    id: 'seed-work-1',
    deviceId: 'seed-system',
    content: '전체 메일로 회신(Reply All) 누르고 동기한테 보내려던 "김 부장님 또 시작이시네ㅋㅋ"를 전사 임원까지 다 들어가게 보냈습니다... 퇴사각일까요?',
    category: '업무/취업',
    tags: ['실수', '메일', '직장생활', '이불킥'],
    aiComfortQuote: '실수는 누구나 합니다. 솔직하고 정중한 사과 한 통이 때로는 전화위복이 될 수 있어요. 오늘 밤은 푹 쉬세요.',
    reactions: { comfort: 42, relate: 68, kick: 125, cheer: 31 },
    reportCount: 0,
    isBlinded: false,
    isSeed: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(), // 45분 전
  },
  {
    id: 'seed-work-2',
    deviceId: 'seed-system',
    content: '면접관님이 "마지막으로 하실 말씀 있으신가요?"라고 하셨는데 너무 긴장한 나머지 "집에 가고 싶습니다"라고 해버렸습니다. 분위기 얼어붙음...',
    category: '업무/취업',
    tags: ['면접', '취준', '긴장', '말실수'],
    aiComfortQuote: '얼마나 간절하고 긴장했으면 그랬을까요! 솔직함이 뜻밖의 인상적인 유머로 기억될지도 모릅니다. 기운 내세요!',
    reactions: { comfort: 54, relate: 39, kick: 88, cheer: 45 },
    reportCount: 0,
    isBlinded: false,
    isSeed: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'seed-work-3',
    deviceId: 'seed-system',
    content: 'Git rebase 명령어를 무심코 메인 브랜치에 강제 푸시(force push)했다가 개발팀 서버 배포가 터졌습니다. 시니어 선배님이랑 2시간 동안 땀 뻘뻘 흘렸네요.',
    category: '업무/취업',
    tags: ['개발', 'Git', '서버장애', '야근'],
    aiComfortQuote: '진정한 개발자는 프로덕션 브랜치를 한번 날려보면서 성장한다고 하죠! 큰 배움의 날이었습니다.',
    reactions: { comfort: 63, relate: 92, kick: 41, cheer: 59 },
    reportCount: 0,
    isBlinded: false,
    isSeed: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },

  // 건강/다이어트
  {
    id: 'seed-diet-1',
    deviceId: 'seed-system',
    content: '오늘부터 진짜 저녁 6시 이후 금식 다이어트 1일차였는데, 밤 11시 반에 홀린 듯이 배달앱 켜서 불닭볶음면에 치즈 2장 얹고 캔맥주 마셨습니다. 내일부터 다시...',
    category: '건강/다이어트',
    tags: ['다이어트', '야식', '작심삼일', '불닭'],
    aiComfortQuote: '오늘의 스트레스를 털어낸 맛있는 한 끼였을 뿐입니다. 죄책감 갖지 말고 내일 아침 물 한 잔으로 산뜻하게 다시 시작해요!',
    reactions: { comfort: 89, relate: 142, kick: 15, cheer: 77 },
    reportCount: 0,
    isBlinded: false,
    isSeed: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'seed-diet-2',
    deviceId: 'seed-system',
    content: '새해 다짐으로 헬스장 1년 회원권 거금 들여 결제했는데, 첫날 러닝머신 8분 걷고 샤워실에서 사우나만 30분 하고 집에 왔습니다. 헬스장 기부천사 등극.',
    category: '건강/다이어트',
    tags: ['헬스', '운동', '작심일일', '헬스장'],
    aiComfortQuote: '헬스장 문턱을 넘고 운동화를 신었다는 사실 자체가 절반의 성공입니다. 내일은 10분만 걸어볼까요?',
    reactions: { comfort: 71, relate: 110, kick: 34, cheer: 83 },
    reportCount: 0,
    isBlinded: false,
    isSeed: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
  },

  // 일상/실수
  {
    id: 'seed-daily-1',
    deviceId: 'seed-system',
    content: '만원 버스 탈 때 카드 찍으면서 기사님 얼굴 보고 당당하게 "수고하셨습니다!" 외치고 내릴 때 "안녕하세요!" 하고 내렸습니다. 버스 안 사람들 다 쳐다봄.',
    category: '일상/실수',
    tags: ['버스', '말실수', '출근길', '민망'],
    aiComfortQuote: '버스 안 모든 사람들에게 뜻밖의 유쾌한 미소를 선물하셨네요! 친절한 마음씨가 앞선 귀여운 실수입니다.',
    reactions: { comfort: 95, relate: 73, kick: 112, cheer: 50 },
    reportCount: 0,
    isBlinded: false,
    isSeed: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: 'seed-daily-2',
    deviceId: 'seed-system',
    content: '비 온다는 일기예보 보고 어젯밤에 우산 현관문 손잡이에 걸어뒀는데, 아침에 신발 신고 핸드폰만 들고 그냥 나와서 비 쫄딱 맞고 출근했습니다.',
    category: '일상/실수',
    tags: ['비', '우산', '건망증', '출근'],
    aiComfortQuote: '준비성만큼은 100점이었는데 아침의 바쁨이 뺏어갔군요. 따뜻한 차 한 잔 드시고 감기 조심하세요!',
    reactions: { comfort: 81, relate: 120, kick: 19, cheer: 64 },
    reportCount: 0,
    isBlinded: false,
    isSeed: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
  },

  // 연애/인간관계
  {
    id: 'seed-rel-1',
    deviceId: 'seed-system',
    content: '짝사랑하는 분한테 "오늘 시간 되시면 커피 한잔할래요?"라고 보낸다는 걸, "회사 3인 단톡방"에 잘못 올렸습니다. 팀장님이 "내가 사줄게"라고 답장하심...',
    category: '연애/인간관계',
    tags: ['짝사랑', '카톡실수', '단톡방', '팀장님'],
    aiComfortQuote: '이불킥이 절로 나오는 순간이지만, 팀장님의 유쾌한 배려로 넘길 수 있을 거예요! 용기는 여전히 멋집니다.',
    reactions: { comfort: 110, relate: 64, kick: 158, cheer: 42 },
    reportCount: 0,
    isBlinded: false,
    isSeed: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },

  // 공부/시험
  {
    id: 'seed-study-1',
    deviceId: 'seed-system',
    content: '자격증 시험 준비한다고 일주일 동안 밤샘 벼락치기하고 고사장에 아침 8시 반에 도착했는데... 시험 날짜가 내일이 아니라 다음 주 토요일이었습니다.',
    category: '공부/시험',
    tags: ['자격증', '시험', '벼락치기', '날짜착각'],
    aiComfortQuote: '일주일 치 복습 시간을 미리 번 셈입니다! 다음 주 시험에서는 분명 여유롭게 만점 받으실 거예요.',
    reactions: { comfort: 67, relate: 45, kick: 31, cheer: 98 },
    reportCount: 0,
    isBlinded: false,
    isSeed: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },

  // 소비/재테크
  {
    id: 'seed-finance-1',
    deviceId: 'seed-system',
    content: '택시비 8,000원 아끼겠다고 심야에 따릉이 자전거 탔다가 지도 잘못 봐서 반대 방향으로 1시간 달렸습니다. 다리 풀려서 결국 15,000원 내고 택시 타고 귀가...',
    category: '소비/재테크',
    tags: ['소비', '따릉이', '길치', '택시비'],
    aiComfortQuote: '8천 원을 아끼려다 유산소 운동 1시간과 인생의 값진 에피소드를 얻으셨습니다. 오늘 밤 꿀잠 예약!',
    reactions: { comfort: 78, relate: 104, kick: 82, cheer: 53 },
    reportCount: 0,
    isBlinded: false,
    isSeed: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
  }
];
